openapi: 3.0.0
info:
  title: "BR BO Repository API (UI)"
  version: 1.0.0
  license:
    name: 'private'
  contact:
    name: mmi
    url: http://www.mmi-media.de
    email: support@mmi-media.de
  description: >
    This is the BR BO Repository API documentation used for UI interaction
  x-logo:
    url: ./logo.svg
servers:
  - url: 'https://example.tld/br-bo-repository/v1'
tags:
  - name: Repository
x-tagGroups:
  - name: Endpoints
    tags:
      - Repository
paths: 
  /business-objects/search:
    post:
      summary: Search for business objects and their related assets
      description: >
        ToDo   
      tags: 
        - Repository
      operationId: searchBusinessObjects
      security:
        - SessionAuthentication: []
      requestBody:
        $ref: '#/components/requestBodies/BusinessObjectSearchRequest'
      responses:
          '200':
            description: Search Result
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/BusinessObject'
          '401':
            $ref: '_errors.yaml#/components/responses/UnauthorizedError'
components:
  securitySchemes:
    SessionAuthentication:
      type: http
      scheme: bearer
  schemas:
    BusinessObject:
      type: object
      properties:
        id:
          type: integer
          format: int64
    BusinessObjectSearchArguments:
      type: object
      properties:
        query:
          type: string
  requestBodies:
    BusinessObjectSearchRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BusinessObjectSearchArguments'

